# Generated by Django 5.2.7 on 2025-11-16 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App')], help_text='Type of notification', max_length=10)),
                ('message_type', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('REMINDER_24H', '24-Hour Reminder'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], help_text='Type of message/event', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read (for in-app notifications)', null=True)),
                ('email_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', help_text='Status of email delivery', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, help_text='Related consultation (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='consultations.consultation')),
                ('user', models.ForeignKey(help_text='User who receives the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_e78525_idx'), models.Index(fields=['consultation'], name='notificatio_consult_a78e63_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['email_status'], name='notificatio_email_s_ffb306_idx'), models.Index(fields=['read_at'], name='notificatio_read_at_392a1c_idx')],
            },
        ),
    ]
