# Generated by Django 5.2.7 on 2025-11-16 11:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Professor title (Dr., Prof., etc.)', max_length=50, null=True)),
                ('department', models.CharField(blank=True, help_text="Professor's department", max_length=100, null=True)),
                ('office_location', models.CharField(blank=True, help_text='Office location for consultations', max_length=200, null=True)),
                ('consultation_duration_default', models.PositiveIntegerField(default=30, help_text='Default consultation duration in minutes (15-240)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)])),
                ('available_days', models.JSONField(blank=True, default=dict, help_text='JSON field with day/time slots for availability')),
                ('max_advance_booking_days', models.PositiveIntegerField(default=30, help_text='Maximum days in advance students can book (1-365)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('buffer_time_between_consultations', models.PositiveIntegerField(default=15, help_text='Buffer time between consultations in minutes (0-120)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor Profile',
                'verbose_name_plural': 'Professor Profiles',
                'db_table': 'professor_profiles',
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['department'], name='professor_p_departm_fb4152_idx')],
            },
        ),
    ]
