# Generated by Django 5.2.7 on 2025-11-16 11:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Consultation title', max_length=200)),
                ('description', models.TextField(help_text='Consultation description/details')),
                ('scheduled_date', models.DateField(help_text='Scheduled date for consultation')),
                ('scheduled_time', models.TimeField(help_text='Scheduled time for consultation')),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duration in minutes (15-240)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', help_text='Current status of consultation', max_length=20)),
                ('booking_created_at', models.DateTimeField(auto_now_add=True, help_text='When booking was created')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When consultation was confirmed by professor', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When consultation was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('google_calendar_event_id', models.CharField(blank=True, help_text='Google Calendar event ID', max_length=255, null=True, unique=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Optional meeting link (for online consultations)', max_length=500, null=True)),
                ('location', models.CharField(blank=True, help_text='Consultation location', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Professor notes after consultation', null=True)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Student rating (1-5) after completion', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True, help_text='Student feedback after completion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(help_text='Professor providing the consultation', on_delete=django.db.models.deletion.CASCADE, related_name='professor_consultations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student who booked the consultation', on_delete=django.db.models.deletion.CASCADE, related_name='student_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultations',
                'ordering': ['-scheduled_date', '-scheduled_time'],
                'indexes': [models.Index(fields=['student'], name='consultatio_student_81001c_idx'), models.Index(fields=['professor'], name='consultatio_profess_5ffc53_idx'), models.Index(fields=['status'], name='consultatio_status_beb187_idx'), models.Index(fields=['scheduled_date', 'scheduled_time'], name='consultatio_schedul_b61862_idx'), models.Index(fields=['google_calendar_event_id'], name='consultatio_google__cd33b0_idx')],
            },
        ),
    ]
